# Generated by Django 4.1.5 on 2023-06-15 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PC_id', models.IntegerField()),
                ('PC_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.IntegerField()),
                ('P_name', models.CharField(max_length=100)),
                ('P_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_description', models.TextField()),
                ('P_date', models.DateField()),
                ('PC_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
